setx XDG_CONFIG_HOME "C:/Users/%USERNAME%/.config/"
setx XDG_DATA_HOME   "C:/Users/%USERNAME%/.local/share/"
setx XDG_STATE_HOME  "C:/Users/%USERNAME%/.local/state/"
setx XDG_BIN_HOME    "C:/Users/%USERNAME%/.local/bin"
setx XDG_LIB_HOME    "C:/Users/%USERNAME%/.local/lib"
setx XDG_CACHE_HOME  "C:/Users/%USERNAME%/.cache"
