alias cp='cp -i'
alias mv='mv -i'
alias ll='ls -lahF --color=always --group-directories-first'
alias cb='cd $OLDPWD'
alias ..='cd ..'
alias df='df -h'
#alias du='du -hsL'
alias vi='vim'
alias openports='netstat -nape --inet'
alias fwhat='find / -name'
alias fwho='find / -user'
alias finf='grep -rl . -e'
alias shareonhttp='python -m SimpleHTTPServer'
alias mc='. /usr/lib/mc/mc-wrapper.sh'
alias rl='readlink -m'
alias me="python3 -c 'import requests,pprint; pprint.pprint(requests.get(\"https://ifconfig.co/json\").json())'"
