" vim: foldmethod=marker formatoptions-=o

source $XDG_CONFIG_HOME/vim/common-before

set viminfofile=$VIMDATA/viminfo
set undodir=$VIMDATA/vimundo//     | call mkdir(&undodir,   'p')

packadd! CamelCaseMotion
packadd! ReplaceWithRegister
packadd! editorconfig-vim
packadd! matchit
packadd! targets.vim
packadd! vim-commentary
packadd! vim-highlightedyank
packadd! vim-indent-object
packadd! vim-sandwich
packadd! vim-unimpaired
packadd! vim-visual-star-search

let g:highlightedyank_highlight_duration = 250

" Set Vim-specific sequences for RGB colors
let &t_8f = "\<Esc>[38;2;%lu;%lu;%lum"
let &t_8b = "\<Esc>[48;2;%lu;%lu;%lum"

" Save as sudo
cnoremap w!! w !sudo tee % >/dev/null

source $VIMCONFIG/common-after
