#!/bin/sh

BRANCH_NAME=$(git branch | grep '*' | sed 's/* //')
ISSUE_NUMBER=`echo "$BRANCH_NAME" | egrep -o '^[0-9]{1,4}'`

if [ -n "$ISSUE_NUMBER" ]
then
	echo -e "\n\nrefs #$ISSUE_NUMBER" "$(cat "$1")" > "$1"
fi
